
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: centralized-workflow
  title: Centralized Workflow Trigger
  description: Triggers a centralized GitHub Actions workflow for building and deploying to JFrog.
spec:
  owner: backstage-team
  type: service

  parameters:
    - title: Repository Information
      required:
        - repo_owner
        - repo_name
        - jfrog_url
      properties:
        repo_owner:
          type: string
          title: Repository Owner
          description: GitHub username or organization that owns the repository
        repo_name:
          type: string
          title: Repository Name
          description: Name of the repository
        jfrog_url:
          type: string
          title: JFrog Artifactory URL
          description: URL of the JFrog Artifactory instance

  steps:
    - id: trigger-workflow
      name: Trigger Centralized Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=${{ parameters.repo_name }}&owner=${{ parameters.repo_owner }}  # ✅ Corrected format
        workflowId: build-and-deploy.yml
        branchOrTagName: main
        workflowInputs:
          repo_url: github.com/${{ parameters.repo_owner }}/${{ parameters.repo_name }}
          jfrog_url: ${{ parameters.jfrog_url }}

  output:
    links:
      - title: View Workflow Run
        url: https://github.com/${{ parameters.repo_owner }}/${{ parameters.repo_name }}/actions
